version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing Maven..."
      - yum update -y
      - yum install -y zip
      - mvn --version

  pre_build:
    commands:
      - echo "Running pre-build steps"
      - mvn clean

  build:
    commands:
      - echo "Building the Spring Boot application"
      - mvn package -DskipTests

  post_build:
    commands:
      - echo "Checking target folder"
      - ls -l target
      - echo "Copying WAR"
      - cp target/*.war .
      - echo "Listing root folder"
      - ls -l
artifacts:
  files:
    - "*.war"
  discard-paths: yes
