version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing Maven..."
      - apt-get update
      - apt-get install -y zip
      - mvn --version

  pre_build:
    commands:
      - echo "Running pre-build steps"
      - mvn clean

  build:
    commands:
      - echo "Building the Spring Boot application"
      - mvn package -DskipTests

  post_build:
    commands:
      - cp target/*.war app.war
      - zip app.zip app.war
      - echo "Artifact zipped as app.zip"
artifacts:
  files:
    - app.zip
  discard-paths: yes
